### ISSUE TITLE
Passage question

### ISSUE THREAD

**Issue by prestwich** [init4tech/zenith#1]
https://github.com/anna-carroll/zenith/blob/main/src/Passage.sol#L33-L44

This is assuming that the host ETH is retrievable somehow?

The non-retrievable design would be to give the RU-ETH to the block builder

**Comment by anna-carroll** [comment]
i think the LOC you linked may have changed so can't tell what you're directly referencing, but - yes, there must be a method to retrieve host tokens & ETH. i've been holding off on adding that for a bit, but can add

**Comment by prestwich** [comment]
closed by #23
